### ISSUE TITLE
Prereqs

### ISSUE THREAD

**Issue by stevealder** [zenetys/rpm-guacamole-server#1]
I believe some prerequisites are missing.  From a plain 'Server w/GUI' CentOS 8.2 install, I am getting the following from execution of your script.  I assume docker binary is required, but what else is? Started feeling like I was back in RPM dependency hell.

Btw, love the idea guys!  Most places I deployment guacamole, internet repos aren't readily available.  Good luck!

**./rpmbuild-docker -d el8
SPECFILE: guacamole-server.spec
SPECDIR: /opt/GUAC_BUILD/rpm-guacamole-server/SPECS
SOURCEDIR: /opt/GUAC_BUILD/rpm-guacamole-server/SOURCES
OUTPUTDIR: /opt/GUAC_BUILD/rpm-guacamole-server
PREBUILDSCRIPT: /opt/GUAC_BUILD/rpm-guacamole-server/prebuild.sh
REPO: none
./rpmbuild-docker: line 232: docker: command not found
./rpmbuild-docker: line 233: docker: command not found
FATAL: failed to build image rpmbuild/el8:c7642b0 for el8**

**Comment by julthomas** [comment]
Hello @stevealder,

Yes indeed you need a functional docker on the build host, the docker command must be in your $PATH. It should then download the base centos 8 image automatically to make the build inside an ephemeral container. It means your build host needs internet access to download the centos 8 image if not already present.

Hope that helps, let us know.

Regards,
Julien

**Comment by julthomas** [comment]
Done in commit bea93ad
